# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  go: 1.17

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - revive
    - nakedret

linters-settings:
  nakedret:
    # Aggressively disallow naked returns
    max-func-lines: 3

issues:
  exclude:
    # This is golangci-lint's EXC0001, but no way to use that collection as an exclude.
    - .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
